# LinuxBaselineDebian role tasks
---
- name: fix /etc/apt/sources.list on generic debian10 box
  replace:
    path: /etc/apt/sources.list
    regexp: '^(deb http:\/\/deb\.debian\.org\/debian buster main)$'
    replace: '# \1'
    backup: yes

- name: apt-get autoremove
  apt:
    autoremove: yes

- name: apt-get install python-apt
  apt:
    name: python-apt
    update_cache: yes
  become: yes

- name: Turn on dircolors
  replace:
    dest: /root/.bashrc
    regexp: '^# eval "`dircolors`"$'
    replace: 'eval "`dircolors`"'

- name: Export LS_Options
  replace:
    dest: /root/.bashrc
    regexp: '^# export LS_OPTIONS=''--color=auto''$'
    replace: 'export LS_OPTIONS=''--color=auto'''

- name: Alias ll to ls -la
  replace:
    dest: /root/.bashrc
    regexp: '^# alias ll=''ls \$LS_OPTIONS -l''$'
    replace: 'alias ll=''ls $LS_OPTIONS -la'''

- name: Alias ll to ls -la
  replace:
    dest: /home/vagrant/.bashrc
    regexp: '^#\s?alias ll=''ls -l''$'
    replace: 'alias ll=''ls -la'''

- name: Set timezone to America/Denver
  timezone:
    name: "America/Denver"
