---
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - import_role: 
        name: LinuxBaseline
      tags:
        - LinuxBaseline

    - import_role:
        name: ca
      tags:
        ca

    # Used by the Ansible OpenSSL modules
    - name: install pip modules
      pip:
        name: pyOpenSSL
        # executable: /usr/bin/pip3
