# LocalHostsFile Role Tasks
---
- name: Add the Linux inventory into /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}"
    state: present
  when: hostvars[item]['ansible_facts']['default_ipv4'] is defined
  with_items:
    - "{{ groups['all'] }}"
  become: yes

- name: Add the Windows inventory into /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_ip_addresses'][0] }} {{ item }}"
    state: present
  when: hostvars[item]['ansible_ip_addresses'] is defined
  with_items:
    - "{{ groups['all'] }}"
  become: yes
